create extension if not exists pgcrypto;

create or replace function public.hedge_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.hedge_config (
  config_key text primary key,
  config_value jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists hedge_config_touch_updated_at on public.hedge_config;
create trigger hedge_config_touch_updated_at
before update on public.hedge_config
for each row execute function public.hedge_touch_updated_at();

insert into public.hedge_config (config_key, config_value)
values
  (
    'automation_enabled',
    '{"enabled": false, "note": "Enable only after dry-run receipts, accounts, adapters, and risk limits are verified."}'::jsonb
  ),
  ('claim_interval_minutes', '{"minutes": 15}'::jsonb),
  (
    'sol_fee_policy',
    '{"network": "solana", "fee_buffer_sol": 0.05, "destination": "hyperliquid"}'::jsonb
  ),
  (
    'mandate',
    '{"venue": "Hyperliquid", "position_side": "short", "buyback_asset": "HEDGE"}'::jsonb
  ),
  (
    'risk_limits',
    '{"max_sol_per_run": 0, "max_short_notional_usd": 0, "max_leverage": 1, "dry_run": true}'::jsonb
  )
on conflict (config_key) do update
set config_value = excluded.config_value,
    updated_at = now();

create table if not exists public.hedge_wallets (
  id uuid primary key default gen_random_uuid(),
  label text not null unique default 'primary',
  sol_fee_wallet_address text,
  hyperliquid_account text,
  sol_exit_wallet_address text,
  token_mint text,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists hedge_wallets_touch_updated_at on public.hedge_wallets;
create trigger hedge_wallets_touch_updated_at
before update on public.hedge_wallets
for each row execute function public.hedge_touch_updated_at();

create table if not exists public.hedge_automation_runs (
  id uuid primary key default gen_random_uuid(),
  run_type text not null default 'claim_bridge_short_buyback_burn',
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  scheduled_for timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists hedge_automation_runs_status_idx
  on public.hedge_automation_runs (status, scheduled_for desc);

create table if not exists public.hedge_terminal_events (
  id bigint generated by default as identity primary key,
  run_id uuid references public.hedge_automation_runs (id) on delete set null,
  event_type text not null default 'automation',
  stage text not null,
  status text not null default 'pending'
    check (status in ('idle', 'pending', 'running', 'succeeded', 'failed', 'skipped')),
  action text not null,
  message text,
  wallet_address text,
  asset text,
  amount numeric(38, 18),
  tx_hash text,
  scan_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists hedge_terminal_events_created_idx
  on public.hedge_terminal_events (created_at desc);

create index if not exists hedge_terminal_events_run_idx
  on public.hedge_terminal_events (run_id, created_at);

create table if not exists public.hedge_position_snapshots (
  id bigint generated by default as identity primary key,
  run_id uuid references public.hedge_automation_runs (id) on delete set null,
  hyperliquid_account text not null,
  dex text not null,
  market text not null,
  side text not null check (side in ('long', 'short')),
  size numeric(38, 18) not null,
  notional_usd numeric(38, 18) not null,
  entry_price numeric(38, 18),
  mark_price numeric(38, 18),
  leverage numeric(18, 8),
  unrealized_pnl_usd numeric(38, 18) not null default 0,
  margin_used_usd numeric(38, 18) not null default 0,
  liquidation_price numeric(38, 18),
  metadata jsonb not null default '{}'::jsonb,
  recorded_at timestamptz not null default now()
);

create index if not exists hedge_positions_market_recorded_idx
  on public.hedge_position_snapshots (dex, market, recorded_at desc);

create table if not exists public.hedge_claims (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.hedge_automation_runs (id) on delete set null,
  source text not null default 'creator_fees',
  asset text not null default 'SOL',
  amount numeric(38, 18) not null,
  wallet_address text,
  tx_hash text,
  scan_url text,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  claimed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.hedge_bridges (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.hedge_automation_runs (id) on delete set null,
  source_chain text not null default 'Solana',
  destination text not null default 'Hyperliquid',
  asset text not null default 'SOL',
  amount numeric(38, 18) not null,
  from_wallet text,
  to_account text,
  tx_hash text,
  scan_url text,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  bridged_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.hedge_short_orders (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.hedge_automation_runs (id) on delete set null,
  hyperliquid_account text not null,
  dex text not null,
  market text not null,
  side text not null default 'short' check (side = 'short'),
  order_type text not null default 'market',
  collateral_usd numeric(38, 18),
  notional_usd numeric(38, 18) not null,
  leverage numeric(18, 8),
  exchange_order_id text,
  tx_hash text,
  scan_url text,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  opened_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.hedge_buybacks (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.hedge_automation_runs (id) on delete set null,
  source_profit_usd numeric(38, 18) not null,
  spend_asset text not null default 'USDC',
  spend_amount numeric(38, 18) not null,
  token_mint text not null,
  tokens_bought numeric(38, 18) not null,
  tx_hash text,
  scan_url text,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  executed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.hedge_burns (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.hedge_automation_runs (id) on delete set null,
  token_mint text not null,
  token_symbol text not null default 'HEDGE',
  amount numeric(38, 18) not null,
  tx_hash text,
  scan_url text,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  burned_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace view public.hedge_public_terminal
with (security_invoker = true)
as
select
  id,
  created_at,
  stage,
  status,
  action,
  message,
  wallet_address,
  asset,
  amount,
  tx_hash,
  scan_url
from public.hedge_terminal_events;

create or replace view public.hedge_latest_positions
with (security_invoker = true)
as
select distinct on (lower(dex), upper(market))
  id,
  recorded_at,
  hyperliquid_account,
  dex,
  market,
  side,
  size,
  notional_usd,
  entry_price,
  mark_price,
  leverage,
  unrealized_pnl_usd,
  margin_used_usd,
  liquidation_price
from public.hedge_position_snapshots
order by lower(dex), upper(market), recorded_at desc;

create or replace view public.hedge_public_totals
with (security_invoker = true)
as
select
  coalesce((
    select sum(amount)
    from public.hedge_claims
    where status = 'succeeded' and upper(asset) = 'SOL'
  ), 0) as total_fees_claimed_sol,
  coalesce((
    select sum(amount)
    from public.hedge_bridges
    where status = 'succeeded' and upper(asset) = 'SOL'
  ), 0) as total_bridged_sol,
  coalesce((
    select sum(spend_amount)
    from public.hedge_buybacks
    where status = 'succeeded'
  ), 0) as total_buyback_value,
  coalesce((
    select sum(amount)
    from public.hedge_burns
    where status = 'succeeded'
  ), 0) as total_tokens_burned;

alter table public.hedge_config enable row level security;
alter table public.hedge_wallets enable row level security;
alter table public.hedge_automation_runs enable row level security;
alter table public.hedge_terminal_events enable row level security;
alter table public.hedge_position_snapshots enable row level security;
alter table public.hedge_claims enable row level security;
alter table public.hedge_bridges enable row level security;
alter table public.hedge_short_orders enable row level security;
alter table public.hedge_buybacks enable row level security;
alter table public.hedge_burns enable row level security;

drop policy if exists "public read hedge terminal" on public.hedge_terminal_events;
create policy "public read hedge terminal"
on public.hedge_terminal_events for select
using (status = 'succeeded');

drop policy if exists "public read hedge positions" on public.hedge_position_snapshots;
create policy "public read hedge positions"
on public.hedge_position_snapshots for select
using (true);

drop policy if exists "public read hedge claims" on public.hedge_claims;
create policy "public read hedge claims"
on public.hedge_claims for select
using (status = 'succeeded');

drop policy if exists "public read hedge bridges" on public.hedge_bridges;
create policy "public read hedge bridges"
on public.hedge_bridges for select
using (status = 'succeeded');

drop policy if exists "public read hedge orders" on public.hedge_short_orders;
create policy "public read hedge orders"
on public.hedge_short_orders for select
using (status = 'succeeded');

drop policy if exists "public read hedge buybacks" on public.hedge_buybacks;
create policy "public read hedge buybacks"
on public.hedge_buybacks for select
using (status = 'succeeded');

drop policy if exists "public read hedge burns" on public.hedge_burns;
create policy "public read hedge burns"
on public.hedge_burns for select
using (status = 'succeeded');

grant select (
  id, created_at, stage, status, action, message, wallet_address, asset,
  amount, tx_hash, scan_url
) on public.hedge_terminal_events to anon, authenticated;

grant select (
  id, recorded_at, hyperliquid_account, dex, market, side, size,
  notional_usd, entry_price, mark_price, leverage, unrealized_pnl_usd,
  margin_used_usd, liquidation_price
) on public.hedge_position_snapshots to anon, authenticated;

grant select (id, run_id, source, asset, amount, wallet_address, tx_hash, scan_url, status, claimed_at, created_at)
on public.hedge_claims to anon, authenticated;

grant select (id, run_id, source_chain, destination, asset, amount, from_wallet, to_account, tx_hash, scan_url, status, bridged_at, created_at)
on public.hedge_bridges to anon, authenticated;

grant select (id, run_id, hyperliquid_account, dex, market, side, order_type, collateral_usd, notional_usd, leverage, exchange_order_id, tx_hash, scan_url, status, opened_at, created_at)
on public.hedge_short_orders to anon, authenticated;

grant select (id, run_id, source_profit_usd, spend_asset, spend_amount, token_mint, tokens_bought, tx_hash, scan_url, status, executed_at, created_at)
on public.hedge_buybacks to anon, authenticated;

grant select (id, run_id, token_mint, token_symbol, amount, tx_hash, scan_url, status, burned_at, created_at)
on public.hedge_burns to anon, authenticated;

grant select on public.hedge_public_terminal to anon, authenticated;
grant select on public.hedge_latest_positions to anon, authenticated;
grant select on public.hedge_public_totals to anon, authenticated;

comment on view public.hedge_public_terminal is
  'Browser-safe verified receipt feed for Hedge the Hedgehog.';

comment on view public.hedge_latest_positions is
  'Latest public Hyperliquid position snapshot for each configured market.';

comment on view public.hedge_public_totals is
  'Verified aggregate creator-fee, bridge, buyback, and burn totals.';
