create extension if not exists pgcrypto;

create or replace function public.bbl_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.bbl_config (
  config_key text primary key,
  config_value jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists bbl_config_touch_updated_at on public.bbl_config;
create trigger bbl_config_touch_updated_at
before update on public.bbl_config
for each row execute function public.bbl_touch_updated_at();

insert into public.bbl_config (config_key, config_value)
values
  (
    'automation_enabled',
    '{"enabled": false, "note": "Enable only after dry-run receipts and limits are verified."}'::jsonb
  ),
  ('claim_interval_minutes', '{"minutes": 15}'::jsonb),
  (
    'sol_fee_policy',
    '{"network": "solana", "gas_buffer_sol": 0.05, "route": "aster"}'::jsonb
  ),
  (
    'flywheel',
    '{"position_asset": "ANSEM", "position_type": "perpetual", "leverage": 5, "buyback_asset": "BBL"}'::jsonb
  ),
  (
    'risk_limits',
    '{"max_collateral_usdt_per_run": 0, "leverage": 5, "dry_run": true}'::jsonb
  )
on conflict (config_key) do update
set config_value = excluded.config_value,
    updated_at = now();

create table if not exists public.bbl_wallets (
  id uuid primary key default gen_random_uuid(),
  label text not null unique default 'primary',
  sol_wallet_address text,
  aster_wallet_address text,
  aster_account text,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bbl_wallets
  add column if not exists aster_wallet_address text,
  add column if not exists aster_account text;

drop trigger if exists bbl_wallets_touch_updated_at on public.bbl_wallets;
create trigger bbl_wallets_touch_updated_at
before update on public.bbl_wallets
for each row execute function public.bbl_touch_updated_at();

create table if not exists public.bbl_automation_runs (
  id uuid primary key default gen_random_uuid(),
  run_type text not null default 'claim_bridge_long_buyback_burn',
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  scheduled_for timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists bbl_automation_runs_status_idx
  on public.bbl_automation_runs (status, scheduled_for desc);

create table if not exists public.bbl_terminal_events (
  id bigint generated by default as identity primary key,
  run_id uuid references public.bbl_automation_runs (id) on delete set null,
  event_type text not null default 'automation',
  stage text not null,
  status text not null default 'pending'
    check (status in ('idle', 'pending', 'running', 'succeeded', 'failed', 'skipped')),
  action text not null,
  message text,
  wallet_address text,
  asset text,
  amount numeric(38, 18),
  tx_hash text,
  scan_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists bbl_terminal_events_created_idx
  on public.bbl_terminal_events (created_at desc);

create index if not exists bbl_terminal_events_run_idx
  on public.bbl_terminal_events (run_id, created_at);

create table if not exists public.bbl_positions (
  id bigint generated by default as identity primary key,
  run_id uuid references public.bbl_automation_runs (id) on delete set null,
  aster_account text not null,
  market text not null default 'ANSEMUSDT',
  side text not null default 'long'
    check (side in ('long', 'short', 'flat')),
  size numeric(38, 18) not null default 0,
  notional_usdc numeric(38, 18) not null default 0,
  entry_price numeric(38, 18),
  mark_price numeric(38, 18),
  leverage numeric(18, 8) not null default 5,
  unrealized_pnl_usdc numeric(38, 18) not null default 0,
  margin_used_usdc numeric(38, 18) not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  recorded_at timestamptz not null default now()
);

alter table public.bbl_positions
  add column if not exists aster_account text;

alter table public.bbl_positions
  alter column market set default 'ANSEMUSDT',
  alter column leverage set default 5;

do $$
declare
  legacy_account_column text := 'hyper' || 'liquid_account';
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'bbl_positions'
      and column_name = legacy_account_column
  ) then
    execute format(
      'alter table public.bbl_positions alter column %I drop not null',
      legacy_account_column
    );
  end if;
end;
$$;

create index if not exists bbl_positions_market_recorded_idx
  on public.bbl_positions (market, recorded_at desc);

create table if not exists public.bbl_claims (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.bbl_automation_runs (id) on delete set null,
  source text not null default 'creator_fees',
  token_symbol text not null default 'SOL',
  amount numeric(38, 18) not null default 0,
  from_wallet text,
  to_wallet text,
  tx_hash text,
  scan_url text,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  metadata jsonb not null default '{}'::jsonb,
  claimed_at timestamptz
);

create table if not exists public.bbl_transfers (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.bbl_automation_runs (id) on delete set null,
  transfer_type text not null default 'sol_fee_route',
  from_wallet text,
  to_wallet text,
  asset text not null default 'SOL',
  amount numeric(38, 18) not null default 0,
  tx_hash text,
  scan_url text,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  metadata jsonb not null default '{}'::jsonb,
  transferred_at timestamptz
);

create table if not exists public.bbl_swaps (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.bbl_automation_runs (id) on delete set null,
  venue text not null default 'Aster',
  from_asset text not null default 'SOL',
  to_asset text not null default 'USDT',
  from_amount numeric(38, 18) not null default 0,
  to_amount numeric(38, 18) not null default 0,
  price numeric(38, 18),
  slippage_bps numeric(18, 8),
  tx_hash text,
  scan_url text,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  metadata jsonb not null default '{}'::jsonb,
  executed_at timestamptz
);

alter table public.bbl_swaps
  alter column venue set default 'Aster',
  alter column from_asset set default 'SOL',
  alter column to_asset set default 'USDT';

create table if not exists public.bbl_long_orders (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.bbl_automation_runs (id) on delete set null,
  aster_account text,
  market text not null default 'ANSEMUSDT',
  side text not null default 'long' check (side in ('long', 'short')),
  order_type text not null default 'market',
  collateral_usdc numeric(38, 18) not null default 0,
  notional_usdc numeric(38, 18) not null default 0,
  leverage numeric(18, 8) not null default 5,
  limit_price numeric(38, 18),
  exchange_order_id text,
  tx_hash text,
  scan_url text,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  metadata jsonb not null default '{}'::jsonb,
  opened_at timestamptz
);

alter table public.bbl_long_orders
  add column if not exists aster_account text;

alter table public.bbl_long_orders
  alter column market set default 'ANSEMUSDT',
  alter column order_type set default 'market',
  alter column leverage set default 5;

create table if not exists public.bbl_burns (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.bbl_automation_runs (id) on delete set null,
  token_symbol text not null default 'BBL',
  amount numeric(38, 18) not null default 0,
  tx_hash text,
  scan_url text,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  metadata jsonb not null default '{}'::jsonb,
  burned_at timestamptz
);

create or replace view public.bbl_public_terminal
with (security_invoker = true)
as
select
  id,
  created_at,
  stage,
  status,
  action,
  message,
  wallet_address,
  asset,
  amount,
  tx_hash,
  scan_url
from public.bbl_terminal_events;

drop view if exists public.bbl_latest_position;
create view public.bbl_latest_position
with (security_invoker = true)
as
select distinct on (upper(market))
  id,
  recorded_at,
  aster_account,
  market,
  side,
  size,
  notional_usdc,
  entry_price,
  mark_price,
  leverage,
  unrealized_pnl_usdc,
  margin_used_usdc
from public.bbl_positions
order by upper(market), recorded_at desc;

alter table public.bbl_config enable row level security;
alter table public.bbl_wallets enable row level security;
alter table public.bbl_automation_runs enable row level security;
alter table public.bbl_terminal_events enable row level security;
alter table public.bbl_positions enable row level security;
alter table public.bbl_claims enable row level security;
alter table public.bbl_transfers enable row level security;
alter table public.bbl_swaps enable row level security;
alter table public.bbl_long_orders enable row level security;
alter table public.bbl_burns enable row level security;

drop policy if exists "public read bbl terminal" on public.bbl_terminal_events;
create policy "public read bbl terminal"
on public.bbl_terminal_events for select using (true);

drop policy if exists "public read bbl positions" on public.bbl_positions;
create policy "public read bbl positions"
on public.bbl_positions for select using (true);

drop policy if exists "public read bbl burns" on public.bbl_burns;
create policy "public read bbl burns"
on public.bbl_burns for select using (true);

grant select on public.bbl_public_terminal to anon, authenticated;
grant select on public.bbl_latest_position to anon, authenticated;

comment on view public.bbl_public_terminal is
  'Browser-safe public receipt feed for the Black Bull Flywheel.';

comment on view public.bbl_latest_position is
  'Browser-safe latest published ANSEMUSDT 5x long position.';
