create extension if not exists pgcrypto;

create or replace function public.longcat_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.longcat_config (
  config_key text primary key,
  config_value jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists longcat_config_touch_updated_at on public.longcat_config;
create trigger longcat_config_touch_updated_at
before update on public.longcat_config
for each row execute function public.longcat_touch_updated_at();

insert into public.longcat_config (config_key, config_value)
values
  ('automation_enabled', '{"enabled": false, "note": "Flip on only after wallet secrets, risk limits, and dry-run checks are configured."}'::jsonb),
  ('claim_interval_minutes', '{"minutes": 15}'::jsonb),
  ('sol_transfer_policy', '{"buffer_sol": 0.05, "send_rule": "send_all_above_buffer_to_hyperliquid_wallet"}'::jsonb),
  ('nlt_definition', '{"label": "native leverage loop"}'::jsonb),
  ('risk_limits', '{"max_order_notional_usdc": 0, "max_leverage": 0, "max_slippage_bps": 0, "dry_run": true}'::jsonb)
on conflict (config_key) do nothing;

insert into public.longcat_config (config_key, config_value)
values ('sol_transfer_policy', '{"buffer_sol": 0.05, "send_rule": "send_all_above_buffer_to_hyperliquid_wallet"}'::jsonb)
on conflict (config_key) do update
set
  config_value = excluded.config_value,
  updated_at = now();

create table if not exists public.longcat_wallets (
  id uuid primary key default gen_random_uuid(),
  label text not null default 'primary',
  sol_wallet_address text,
  hyperliquid_wallet_address text,
  hyperliquid_perp_account text,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (label)
);

drop trigger if exists longcat_wallets_touch_updated_at on public.longcat_wallets;
create trigger longcat_wallets_touch_updated_at
before update on public.longcat_wallets
for each row execute function public.longcat_touch_updated_at();

create table if not exists public.longcat_automation_runs (
  id uuid primary key default gen_random_uuid(),
  run_type text not null default 'claim_route_long',
  status text not null default 'pending' check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  scheduled_for timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists longcat_automation_runs_status_idx
  on public.longcat_automation_runs (status, scheduled_for desc);

create table if not exists public.longcat_terminal_events (
  id bigint generated by default as identity primary key,
  run_id uuid references public.longcat_automation_runs (id) on delete set null,
  event_type text not null default 'system',
  stage text not null,
  status text not null default 'pending' check (status in ('idle', 'pending', 'running', 'succeeded', 'failed', 'skipped')),
  action text not null,
  message text,
  wallet_address text,
  asset text,
  amount numeric(38, 18),
  tx_hash text,
  scan_url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists longcat_terminal_events_created_idx
  on public.longcat_terminal_events (created_at desc);

create index if not exists longcat_terminal_events_run_idx
  on public.longcat_terminal_events (run_id, created_at);

create table if not exists public.longcat_positions (
  id bigint generated by default as identity primary key,
  run_id uuid references public.longcat_automation_runs (id) on delete set null,
  hyperliquid_account text not null,
  market text not null default 'CASHCAT',
  side text not null default 'long' check (side in ('long', 'short', 'flat')),
  size numeric(38, 18) not null default 0,
  notional_usdc numeric(38, 18) not null default 0,
  entry_price numeric(38, 18),
  mark_price numeric(38, 18),
  leverage numeric(18, 8) not null default 0,
  unrealized_pnl_usdc numeric(38, 18) not null default 0,
  margin_used_usdc numeric(38, 18) not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  recorded_at timestamptz not null default now()
);

create index if not exists longcat_positions_market_recorded_idx
  on public.longcat_positions (market, recorded_at desc);

create table if not exists public.longcat_claims (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.longcat_automation_runs (id) on delete set null,
  source text not null default 'fees',
  token_symbol text not null default 'SOL',
  amount numeric(38, 18) not null default 0,
  from_wallet text,
  to_wallet text,
  tx_hash text,
  scan_url text,
  status text not null default 'pending' check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  metadata jsonb not null default '{}'::jsonb,
  claimed_at timestamptz
);

create table if not exists public.longcat_transfers (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.longcat_automation_runs (id) on delete set null,
  transfer_type text not null default 'sol_to_hyperliquid_wallet',
  from_wallet text,
  to_wallet text,
  asset text not null,
  amount numeric(38, 18) not null default 0,
  tx_hash text,
  scan_url text,
  status text not null default 'pending' check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  metadata jsonb not null default '{}'::jsonb,
  transferred_at timestamptz
);

create table if not exists public.longcat_swaps (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.longcat_automation_runs (id) on delete set null,
  venue text,
  from_asset text not null default 'SOL',
  to_asset text not null default 'USDC',
  from_amount numeric(38, 18) not null default 0,
  to_amount numeric(38, 18) not null default 0,
  price numeric(38, 18),
  slippage_bps numeric(18, 8),
  tx_hash text,
  scan_url text,
  status text not null default 'pending' check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  metadata jsonb not null default '{}'::jsonb,
  executed_at timestamptz
);

create table if not exists public.longcat_long_orders (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.longcat_automation_runs (id) on delete set null,
  hyperliquid_account text,
  market text not null default 'CASHCAT',
  side text not null default 'long' check (side in ('long', 'short')),
  order_type text not null default 'market',
  collateral_usdc numeric(38, 18) not null default 0,
  notional_usdc numeric(38, 18) not null default 0,
  leverage numeric(18, 8) not null default 0,
  limit_price numeric(38, 18),
  exchange_order_id text,
  tx_hash text,
  scan_url text,
  status text not null default 'pending' check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  metadata jsonb not null default '{}'::jsonb,
  opened_at timestamptz
);

create table if not exists public.longcat_burns (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.longcat_automation_runs (id) on delete set null,
  token_symbol text not null default 'LONGCAT',
  amount numeric(38, 18) not null default 0,
  tx_hash text,
  scan_url text,
  status text not null default 'pending' check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  metadata jsonb not null default '{}'::jsonb,
  burned_at timestamptz
);

create or replace view public.longcat_public_terminal as
select
  id,
  created_at,
  stage,
  status,
  action,
  message,
  wallet_address,
  asset,
  amount,
  tx_hash,
  scan_url
from public.longcat_terminal_events;

create or replace view public.longcat_latest_position as
select distinct on (upper(market))
  id,
  recorded_at,
  hyperliquid_account,
  market,
  side,
  size,
  notional_usdc,
  entry_price,
  mark_price,
  leverage,
  unrealized_pnl_usdc,
  margin_used_usdc
from public.longcat_positions
order by upper(market), recorded_at desc;

alter table public.longcat_config enable row level security;
alter table public.longcat_wallets enable row level security;
alter table public.longcat_automation_runs enable row level security;
alter table public.longcat_terminal_events enable row level security;
alter table public.longcat_positions enable row level security;
alter table public.longcat_claims enable row level security;
alter table public.longcat_transfers enable row level security;
alter table public.longcat_swaps enable row level security;
alter table public.longcat_long_orders enable row level security;
alter table public.longcat_burns enable row level security;

drop policy if exists "public read terminal events" on public.longcat_terminal_events;
create policy "public read terminal events"
on public.longcat_terminal_events
for select
using (true);

drop policy if exists "public read cashcat positions" on public.longcat_positions;
create policy "public read cashcat positions"
on public.longcat_positions
for select
using (true);

drop policy if exists "public read burns" on public.longcat_burns;
create policy "public read burns"
on public.longcat_burns
for select
using (true);

comment on table public.longcat_terminal_events is
  'Append-only public receipt feed for Longcat claims, sends, swaps, perp deposits, Cashcat orders, and burns.';

comment on view public.longcat_public_terminal is
  'Browser-safe terminal feed. Query with order=created_at.desc and a limit from the Supabase REST API.';

comment on view public.longcat_latest_position is
  'Browser-safe latest market position readout for publishing the Cashcat long backing the native leverage loop.';
